# -*- coding: utf-8 -*-
"""Pre-build check: are all macros referenced in the body defined by the numeric
macro files?

Numeric macro files (see NUM_FILES): after the third-round rewrite the body only
references numbers_theory.tex, generated by code/analysis/make_theory_macros.py
from logs/ and results/; numbers.tex is legacy from an older version (no longer
\\input by main.tex).

Motivation: every number in main.tex is referenced via a \\newcommand macro. If
even one macro is undefined (e.g. a statistic that is NaN under the current data
and skipped by the generation script), pdflatex reports "Undefined control
sequence" and stops far away, making debugging very costly. This script surfaces
the problem before the build and prints the missing list directly.

It also reverse-checks for macros that are defined but never referenced in the
body (dead macros), to avoid the illusion that "all numbers made it into the
paper" when in fact none were used.

Usage:
  python check_macros.py            # report only
  python check_macros.py --strict   # exit code 1 if any are missing (for CI / pipelines)
"""
import argparse
import io
import os
import re
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))


def _find_root(d):
    """Walk up to the top level that contains both code/ and paper/; independent of the script's own depth."""
    while os.path.dirname(d) != d:
        if os.path.isdir(os.path.join(d, "code")) and os.path.isdir(os.path.join(d, "paper")):
            return d
        d = os.path.dirname(d)
    return d


_ROOT_ = _find_root(_HERE)
_CODE_ = os.path.join(_ROOT_, "code")
_ROOT = _ROOT_
PAPER = os.path.join(_ROOT, "paper")
TABDIR = os.path.join(_ROOT, "tables")

# Source files for the paper's numeric macros. After the third-round rewrite the
# body only references numbers_theory.tex; numbers.tex is legacy (kept in paper/
# but no longer \input).
NUM_FILES = ("numbers_theory.tex", "numbers.tex")

# These are built into LaTeX / packages; when present they count as defined
BUILTIN = {
    "text", "mathrm", "mathbf", "mathcal", "mathbb", "hat", "bar", "tilde",
    "sqrt", "frac", "sum", "prod", "int", "log", "exp", "min", "max", "arg",
    "top", "mid", "bottom", "alpha", "beta", "gamma", "delta", "epsilon",
    "eta", "theta", "kappa", "lambda", "mu", "nu", "xi", "pi", "rho", "sigma",
    "tau", "phi", "chi", "psi", "omega", "Lambda", "Sigma", "Phi", "Psi",
    "Omega", "Theta", "Delta", "Gamma", "times", "cdot", "pm", "leq", "geq",
    "neq", "approx", "sim", "propto", "in", "subset", "forall", "exists",
    "nabla", "partial", "infty", "to", "rightarrow", "Rightarrow", "left",
    "right", "big", "Big", "bigg", "Bigg", "begin", "end", "label", "ref",
    "cite", "citep", "citet", "includegraphics", "caption", "centering",
    "item", "itemize", "enumerate", "textbf", "textit", "emph", "vskip",
    "noindent", "paragraph", "section", "subsection", "subsubsection",
    "title", "author", "date", "maketitle", "input", "bibliography",
    "bibliographystyle", "hline", "toprule", "midrule", "bottomrule",
    "multicolumn", "small", "sc", "footnote", "url", "hypersetup", "documentclass",
    "usepackage", "newcommand", "renewcommand", "def", "operatorname", "textwidth",
    "linewidth", "columnwidth", "hspace", "vspace", "quad", "qquad", "hfill",
    "Vert", "vert", "langle", "rangle", "colon", "star", "dagger", "circ",
    "bullet", "dagger", "dots", "ldots", "dotsb", "space", "rlap", "llap",
    "smash", "raisebox", "parbox", "resizebox", "scalebox", "scriptsize",
    "tiny", "large", "Large", "LARGE", "huge", "Huge", "normalsize", "bf",
    "it", "rm", "tt", "sf", "sl",     "displaystyle", "textstyle", "Bigl", "Bigr", "bigl", "bigr", "biggl",
    "biggr", "Biggl", "Biggr", "Longleftrightarrow", "longleftrightarrow",
    "Longrightarrow", "longleftarrow", "Leftrightarrow", "Leftarrow",
    "eqref", "appendix", "mapsto", "longmapsto", "perp", "square",
    "textcolor", "texttt", "textrm", "textsf", "textnormal", "underbrace",
    "overbrace", "zeta", "iota", "upsilon", "varepsilon", "varphi", "varrho",
    "varsigma", "vartheta", "notag", "nonumber", "ensuremath", "ifthenelse",
    "newcolumntype", "cline", "tiny", "scriptsize", "footnotesize",
    "normalsize", "small", "large", "Large", "LARGE", "huge", "Huge",
    "relax", "let", "edef", "gdef", "xdef", "ifx", "else", "fi", "csname",
    "endcsname", "expandafter", "noexpand", "ignorespaces", "unskip", "protect",
    "arraystretch", "tabcolsep", "abovecaptionskip", "belowcaptionskip",
    "par", "hbox", "vbox", "halign", "valign", "cr", "noalign", "omit",
    "ast", "dot", "ddot", "ge", "le", "leq", "geq", "ll", "gg", "circ",
    "prime", "tilde", "widehat", "widetilde", "overline", "underline",
    "stackrel", "overset", "underset", "binom", "choose", "pmod", "bmod",
    "mathrm", "mathsf", "mathtt", "mathnormal", "boldsymbol", "bm",
    "LaTeX", "TeX", "BibTeX", "XeTeX", "LuaTeX",
    # Theorem environments: main.tex's preamble uses
    # \theoremstyle{plain}\newtheorem{prop}{...}; these are built-in LaTeX
    # commands, and omitting them would misreport them as "referenced but NOT
    # defined".
    "newtheorem", "theoremstyle", "theorem", "proof", "qedhere", "MakeUppercase",
    "fbox", "setlength", "texorpdfstring",
    # ---- newly used during the third-round paper rewrite (omitting would
    #      misreport MISSING) ----
    "tfrac", "succeq", "wedge", "bigm", "bigl", "bigr", "notag", "nonumber",
    "textsuperscript", "textsubscript", "left", "right", "displaystyle",
    "mathrm", "operatorname", "middle", "varnothing", "geqslant", "leqslant",
    "triangleq", "bm", "mathds", "textquotedblleft", "textquotedblright",
    # 2026-09-16: three standard math operators that were misreported when
    # running --strict (built into the LaTeX kernel)
    "equiv", "inf", "sup", "lim", "limsup", "liminf", "det", "dim", "ker",
    "deg", "gcd", "lcm", "sin", "cos", "tan", "sinh", "cosh", "tanh", "cot",
    "sec", "csc", "arcsin", "arccos", "arctan", "log", "ln", "lg", "Re", "Im",
    "lfloor", "rfloor", "lceil", "rceil", "vert", "Vert", "|", "{", "}",
}


def read(path):
    with io.open(path, "r", encoding="utf-8", errors="replace") as f:
        return f.read()


def strip_comments(s):
    out = []
    for line in s.splitlines():
        # drop everything after an unescaped %
        buf, i = [], 0
        while i < len(line):
            c = line[i]
            if c == "\\" and i + 1 < len(line):
                buf.append(line[i:i + 2])
                i += 2
                continue
            if c == "%":
                break
            buf.append(c)
            i += 1
        out.append("".join(buf))
    return "\n".join(out)


def defined_macros():
    """Collect all "defined" control sequences.

    Looking only at numbers.tex is insufficient: main.tex's own preamble defines
    \\cD \\cL \\tr \\Var \\Cov \\Eop \\Ncal \\Real \\todo, and the ICLR template's
    math_commands.tex defines a large batch more. Omitting them would misreport
    normal references as missing.
    """
    sources = [os.path.join(PAPER, "main.tex"),
               os.path.join(PAPER, "iclr2027", "math_commands.tex")]
    sources += [os.path.join(PAPER, f) for f in NUM_FILES]
    defs, nums = set(), set()
    for p in sources:
        if not os.path.isfile(p):
            continue
        s = strip_comments(read(p))
        got = set()
        for pat in (r"\\newcommand\*?\{\\([A-Za-z]+)\}",
                    r"\\renewcommand\*?\{\\([A-Za-z]+)\}",
                    r"\\providecommand\*?\{\\([A-Za-z]+)\}",
                    r"\\DeclareRobustCommand\*?\{\\([A-Za-z]+)\}",
                    r"\\DeclareMathOperator\*?\{\\([A-Za-z]+)\}",
                    r"\\def\\([A-Za-z]+)"):
            got |= set(re.findall(pat, s))
        defs |= got
        if os.path.basename(p) in NUM_FILES:
            nums |= got
    return defs, nums


def referenced_macros():
    texts = [(os.path.join(PAPER, "main.tex"), read(os.path.join(PAPER, "main.tex")))]
    if os.path.isdir(TABDIR):
        for fn in sorted(os.listdir(TABDIR)):
            if fn.endswith(".tex"):
                p = os.path.join(TABDIR, fn)
                texts.append((p, read(p)))
    for extra in ("macros.tex",):
        p = os.path.join(PAPER, extra)
        if os.path.isfile(p):
            texts.append((p, read(p)))

    refs = {}
    for path, raw in texts:
        s = strip_comments(raw)
        # take only contiguous letters: in \approx0.3 the control sequence is
        # \approx, not \approx0
        for m in re.finditer(r"\\([A-Za-z]+)", s):
            name = m.group(1)
            if name in BUILTIN:
                continue
            refs.setdefault(name, set()).add(os.path.relpath(path, _ROOT))
    return refs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--strict", action="store_true")
    args = ap.parse_args()

    defs, nums = defined_macros()
    refs = referenced_macros()
    # Only definitions in numbers.tex count as "this number is actually used";
    # the hundreds of internal macros in the style files don't, otherwise the
    # dead-macro list would be all noise.
    used_by_paper = {k for k in refs if k in nums}
    missing = sorted(k for k in refs if k not in defs)
    dead = sorted(nums - used_by_paper)
    # macro names containing digits are illegal in LaTeX (control sequences may
    # only consist of letters)
    illegal = sorted(k for k in nums if not k.isalpha())

    print("defined in %s : %d" % ("+".join(NUM_FILES), len(nums)))
    print("defined anywhere       : %d" % len(defs))
    print("referenced (non-builtin): %d" % len(refs))
    print("matched                : %d" % len(used_by_paper))

    if illegal:
        print("\n[ILLEGAL] macro name contains digits -> \\newcommand causes a fatal error, entire build fails:")
        for k in illegal:
            print("   \\%s" % k)
    else:
        print("\n[ILLEGAL] none -- all macro names are pure letters")

    if missing:
        print("\n[MISSING] referenced but NOT defined -> pdflatex will error:")
        for k in missing:
            print("   \\%s   <- %s" % (k, ", ".join(sorted(refs[k]))))
    else:
        print("\n[MISSING] none -- all macros referenced in the body are defined")

    if dead:
        print("\n[DEAD] defined in the number-macro file but never referenced in the body (%d):" % len(dead))
        line = "   "
        for k in dead:
            if len(line) + len(k) > 96:
                print(line)
                line = "   "
            line += k + "  "
        if line.strip():
            print(line)

    if (missing or illegal) and args.strict:
        sys.exit(1)


if __name__ == "__main__":
    main()
