# -*- coding: utf-8 -*-
"""从 refs_raw.json（arXiv 官方页面抓取，已核实）生成 references.bib。

原则：
  - arXiv 条目全部来自抓取结果，标题/作者/年份**逐字照抄**，不手改；
  - 非 arXiv 的经典文献（kNN / k-means / CH / MNIST / COPA）手工录入，均为公开可查条目；
  - 任何无法核实的条目一律写成 % TODO 注释，不伪造。
"""
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = os.path.join(HERE, "refs_raw.json")

# (bibkey, arXiv编号, 备注)  —— 编号全部已核实
MAP = [
    ("lipman2023flowmatching", "2210.02747", ""),
    ("liu2023rectifiedflow", "2209.03003", ""),
    ("tong2024cfm", "2302.00482", ""),
    ("song2023consistency", "2303.01469", ""),
    ("yang2024consistencyfm", "2407.02398", ""),
    ("frans2024shortcut", "2410.12557", ""),
    ("geng2025meanflows", "2505.13447", ""),
    ("salimans2022progressivedistill", "2202.00512", ""),
    ("yin2024dmd", "2311.18828", ""),
    ("liu2024instaflow", "2309.06380", ""),
    ("esser2024sd3", "2403.03206", ""),
    ("chi2023diffusionpolicy", "2303.04137", ""),
    ("wang2023diffusionql", "2208.06193", ""),
    ("nguyen2026bfq", "2606.10613", ""),
    ("li2026ofp", "2603.12480", ""),
    ("mvp2026", "2602.13810", ""),
    ("lps2026", "2603.05296", ""),
    ("flame2026", "2602.01606", ""),
    ("fan2026", "2605.01663", ""),
    ("letitbesimple2026", "2606.05737", ""),
    ("onestepfm2026", "2606.22752", ""),
    ("kynkaanniemi2019prdc", "1904.06991", ""),
    ("kolouri2019gsw", "1902.00434", ""),
    ("agarwal2021precipice", "2108.13264", ""),
    ("fu2020d4rl", "2004.07219", ""),
    ("park2025ogbench", "2410.20092", ""),
    ("liu2023libero", "2306.03310", ""),
]

MANUAL = """
@article{cover1967nn,
  title   = {Nearest neighbor pattern classification},
  author  = {Cover, Thomas M. and Hart, Peter E.},
  journal = {IEEE Transactions on Information Theory},
  volume  = {13}, number = {1}, pages = {21--27}, year = {1967}
}

@article{lloyd1982,
  title   = {Least squares quantization in {PCM}},
  author  = {Lloyd, Stuart P.},
  journal = {IEEE Transactions on Information Theory},
  volume  = {28}, number = {2}, pages = {129--137}, year = {1982}
}

@inproceedings{macqueen1967,
  title     = {Some methods for classification and analysis of multivariate observations},
  author    = {MacQueen, James},
  booktitle = {Proc. 5th Berkeley Symposium on Mathematical Statistics and Probability},
  pages     = {281--297}, year = {1967}
}

@article{calinski1974,
  title   = {A dendrite method for cluster analysis},
  author  = {Cali{\\'n}ski, Tadeusz and Harabasz, Jerzy},
  journal = {Communications in Statistics},
  volume  = {3}, number = {1}, pages = {1--27}, year = {1974}
}

@article{lecun1998mnist,
  title   = {Gradient-based learning applied to document recognition},
  author  = {LeCun, Yann and Bottou, L{\\'e}on and Bengio, Yoshua and Haffner, Patrick},
  journal = {Proceedings of the IEEE},
  volume  = {86}, number = {11}, pages = {2278--2324}, year = {1998}
}

@inproceedings{li2026nofreelunch,
  title     = {No Free Lunch in Few-Step Flow Matching for Conformal Prediction},
  author    = {Li, Ziyun and Bostr{\\"o}m, Henrik},
  booktitle = {Proceedings of the 15th Symposium on Conformal and Probabilistic
               Prediction with Applications ({COPA})},
  series    = {Proceedings of Machine Learning Research},
  volume    = {329}, pages = {1078--1083}, year = {2026}
}

@misc{iclr2027cfp,
  title  = {{ICLR} 2027 Call for Papers and Author Guidelines},
  author = {{ICLR} 2027 Program Committee},
  year   = {2026},
  note   = {Abstract deadline 18 Sep 2026 AoE; paper deadline 25 Sep 2026 AoE;
            main text 9 pages excluding references. \\url{https://iclr.cc/Conferences/2027/CallForPapers}}
}
"""


def bibkey_from_authors(authors, year):
    if not authors:
        return "anon"
    last = authors[0].split(",")[0].strip()
    last = "".join(ch for ch in last if ch.isalnum())
    return (last + str(year)).lower()


def main():
    raw = {}
    for e in json.load(io.open(RAW, encoding="utf-8")):
        raw[e["id"]] = e
    out = ["%% AUTO-GENERATED by paper/make_bib.py from arXiv metadata (verified).",
           "%% 非 arXiv 条目为手工录入的公开经典文献；任何未核实内容均以 TODO 注释标出。",
           ""]
    miss = []
    for key, aid, note in MAP:
        e = raw.get(aid)
        if e is None or not e.get("title"):
            miss.append((key, aid))
            out.append("%% TODO: 未核实的条目 %s (arXiv:%s) —— 请勿在未核实前引用" % (key, aid))
            continue
        year = e["date"].split("/")[0]
        authors = " and ".join(e["authors"])
        lines = ["@article{%s," % key,
                 "  title   = {%s}," % e["title"],
                 "  author  = {%s}," % authors,
                 "  journal = {arXiv preprint arXiv:%s}," % aid,
                 "  year    = {%s}" % year]
        if e.get("comments"):
            cm = e["comments"].replace("this https URL", "").strip()
            if cm:
                lines[-1] += ","
                lines.append("  note    = {%s}" % cm[:120])
        lines.append("}")
        out.append("\n".join(lines))
    out.append(MANUAL)
    with io.open(os.path.join(HERE, "references.bib"), "w", encoding="utf-8") as f:
        f.write("\n\n".join(out) + "\n")
    print("entries:", len(MAP), "| missing:", miss)


if __name__ == "__main__":
    main()
